name: 'Check Compatibility'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # See: https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#synthetic-json-data
      - name: Download synthetic rd patient record
        run: curl -f -L https://dnpm-dip.net/api/rd/fake/data/patient-record -o ./src/test/resources/mv64e-rd-fake-patient.json

      - name: Run tests
        run: ./gradlew test
